# -*- coding: utf-8 -*-
"""Yuran Fernandes 45 Minutes of Action

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168aNgiBI40wB1E5giqx4XtxCmUSXhTvP
"""

pip install -U mplsoccer

font_normal = FontManager('https://raw.githubusercontent.com/google/fonts/main/apache/roboto/'
                          'Roboto%5Bwdth,wght%5D.ttf')
font_italic = FontManager('https://raw.githubusercontent.com/google/fonts/main/apache/roboto/'
                          'Roboto-Italic%5Bwdth,wght%5D.ttf')
font_bold = FontManager('https://raw.githubusercontent.com/google/fonts/main/apache/robotoslab/'
                        'RobotoSlab%5Bwght%5D.ttf')

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/World Cup Project/Yuran Fernandes vs Persib 45 Minutes of Action.csv')
df.head()

df.info()

def_stat = df.groupby(['Event'])['Mins'].count().reset_index()
def_stat.rename({'Mins' : 'def_stats'}, axis = 'columns', inplace=True)

def_stat

"""##PIZZA RADAR CHART"""

from mplsoccer import PyPizza, FontManager

# parameter and value list
params = ['Clearance', 'Intercept', 'Pressing', 'Tackle']
values = [5, 5, 1, 1]

# instantiate PyPizza class
baker = PyPizza(
    params=params,                  # list of parameters
    straight_line_color="#F2F2F2",  # color for straight lines
    straight_line_lw=1,             # linewidth for straight lines
    straight_line_limit=5.0,        # max limit of straight lines
    last_circle_lw=0,               # linewidth of last circle
    other_circle_lw=0,              # linewidth for other circles
    inner_circle_size=0.4,          # size of inner circle
)

# plot pizza
fig, ax = baker.make_pizza(
    values,                     # list of values
    figsize=(8, 8),             # adjust figsize according to your need
    color_blank_space="same",   # use same color to fill blank space
    blank_alpha=0.4,            # alpha for blank-space colors
    param_location=5.5,         # where the parameters will be added
    kwargs_slices=dict(
        facecolor="cornflowerblue", edgecolor="#F2F2F2",
        zorder=2, linewidth=1
    ),                          # values to be used when plotting slices
    kwargs_params=dict(
        color="#000000", fontsize=20,
        fontproperties=font_normal.prop, va="center"
    ),                          # values to be used when adding parameter
    kwargs_values=dict(
        color="#000000", fontsize=20,
        fontproperties=font_normal.prop, zorder=3,
        bbox=dict(
            edgecolor="#000000", facecolor="cornflowerblue",
            boxstyle="round,pad=0.2", lw=1
        )
    )                           # values to be used when adding parameter-values
)

# add title
fig.text(
    0.515, 0.97, "Yuran Fernandes - PSM Makassar", size=18,
    ha="center", fontproperties=font_bold.prop, color="#000000"
)

# add subtitle
fig.text(
    0.515, 0.942,
    "45 Minutes of Actions vs Persib Bandung",
    size=15,
    ha="center", fontproperties=font_bold.prop, color="#000000"
)

plt.show()

"""#HEATMAP ACTION"""

import matplotlib.patheffects as path_effects
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap
from scipy.ndimage import gaussian_filter

from mplsoccer import Pitch, VerticalPitch, FontManager, Sbopen

df['X'] = df.X + 5

# setup pitch
pitch = Pitch(pitch_type='statsbomb', line_zorder=2,
              pitch_color='#22312b', line_color='#efefef')
# draw
fig, ax = pitch.draw(figsize=(10, 10))
fig.set_facecolor('#22312b')
bin_statistic = pitch.bin_statistic(df.X, df.Y, statistic='count', bins=(25, 25))
bin_statistic['statistic'] = gaussian_filter(bin_statistic['statistic'], 2)
pcm = pitch.heatmap(bin_statistic, ax=ax, cmap='hot', edgecolors='#22312b')
# Add the colorbar and format off-white
cbar = fig.colorbar(pcm, ax=ax, shrink=0.6)
cbar.outline.set_edgecolor('#efefef')
cbar.ax.yaxis.set_tick_params(color='#efefef')
ticks = plt.setp(plt.getp(cbar.ax.axes, 'yticklabels'), color='#efefef')
# add title
fig.text(
    0.45, 0.97, "Yuran Fernandes - PSM Makassar", size=25,
    ha="center", fontproperties=font_bold.prop, color="#efefef"
)

# add subtitle
fig.text(
    0.45, 0.942,
    "45 Minutes of Actions vs Persib Bandung",
    size=20,
    ha="center", fontproperties=font_bold.prop, color="#efefef"
)

# add subtitle
fig.text(
    0.45, 0.915,
    "Data by Naufal Akmal",
    size=15,
    ha="center", fontproperties=font_bold.prop, color="#efefef"
)